### ISSUE TITLE
CiviSEPA hides invoice button for contributions

### ISSUE THREAD

**Issue by ghost** [Project60/org.project60.sepa#356]
As of version 4.6, CiviCRM [supports the creation of invoices for contributions](http://gitbook.civicrm.org/contributions/invoicing.html). This is not possible, when the CiviSEPA module is active, because it overwrites [/templates/CRM/Contribute/Form/ContributionView.tpl](https://github.com/Project60/org.project60.sepa/blob/master/templates/CRM/Contribute/Form/ContributionView.tpl) which is based on an old version (4.3) that does not contain all template changes.

diff file:
[ContributionView.txt](https://github.com/Project60/org.project60.sepa/files/87458/ContributionView.txt)

**Comment by systopia** [comment]
Yes, we definitely need to change this asap. I didn't know that was in there.

@tttp: This is still some of your code, right? Can you remember why you included this in the first place?

**Comment by magnolia61** [comment]
When I remove /templates/CRM/Contribute/Form/ContributionView.tpl from CiviSEPA the invoice buttons return and I still get the button with the mandate options in civicrm 4.6.9. Happy with that!
So unless Xavier remembers the initial inclusion I believe it is safe to delete this file.

**Comment by tttp** [comment]
I think I remember and was a temporary fix... that has long been fixed in
the core and is past its due date indeed.

One less file, me like it!

**Comment by systopia** [comment]
aaaand it's gone. Makes *me* happy as well :)

**Comment by Fabian-SYSTOPIA** [comment]
It seems like this bug is back - using 4.6.24 and CiviSEPA 1.2.4beta1

**Comment by systopia** [comment]
Seems to be related to the invoicing functions.

**Comment by systopia** [comment]
released with 1.2.5.beta2
