### ISSUE TITLE
PaymentProcessor: override billing address mandatory

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#372]
With CiviCRM 4.6.10+ the billing address became mandatory for donation pages. However, there should be a way of overriding this, so people can use their donation pages the way they used to...

See also: [CRM-17603](https://issues.civicrm.org/jira/browse/CRM-17603)

**Comment by systopia** [comment]
fixed in ``1.2.2``. Will close ticket when merged to ``master``

**Comment by magnolia61** [comment]
when I use 1.2.2beta1 on civicrm 4.6.14 everything seems to work.
But I am still presented a billing address block which is mandatory.

**Comment by systopia** [comment]
> [...] on event pages the billing block still appears.

Yes, event pages are not fully supported yet (no funding)

Thanks for testing!
